trigger:
  - main
# Your pipeline trigger definition goes here

variables:
  myVariable: 

jobs:
- job: MyJob
  steps:
  - script: echo This task will always run
  
  - script: echo This task will only run if myVariable is true
    condition: eq(variables['myVariable'], 'true')

  - script: echo This task will always run